// Objective-C API for talking to solana_wallet/spider Go package.
//   gobind -lang=objc solana_wallet/spider
//
// File is generated by gobind. Do not edit.

#ifndef __Spider_H__
#define __Spider_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull SpiderEthWalletDemo(NSString* _Nullable words);

FOUNDATION_EXPORT double SpiderFetchEthBalance(NSString* _Nullable rawaddress);

#endif
