
// Objective-C API for talking to the following Go packages
//
//	solana_wallet/spider
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Spider_FRAMEWORK_H__
#define __Spider_FRAMEWORK_H__

#include "Spider.objc.h"
#include "Universe.objc.h"

#endif
